name: Java

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle check
      run: ./gradlew check
    - name: Jacoco report
      run: ./gradlew build jacocoTestReport
    - name: Code Cov
      run: bash <(curl -s https://codecov.io/bash)
   
